### ISSUE TITLE
Git Repository fails

### ISSUE THREAD

**Issue by mzbroch** [nautobot/nautobot-app-design-builder#39]
### Environment
* Python version:  
* Nautobot version:  
* design-builder version:  

### Expected Behavior

Creation of Git Repository fails

### Observed Behavior

Creation of Git Repository is possible

### Steps to Reproduce
1. Create Git Repository2. 
```
git_repositories:
  - name: backups
    remote_url: "https://github.com/nautobot/demo-gc-backups"
    branch: main

```

```
Traceback (most recent call last):
  File "/usr/local/bin/nautobot-server", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/nautobot/core/cli/__init__.py", line 54, in main
    run_app(
  File "/usr/local/lib/python3.8/site-packages/nautobot/core/runner/runner.py", line 263, in run_app
    management.execute_from_command_line([runner_name, command] + command_args)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/source/design_builder/management/commands/test_render_networktocode_designs.py", line 69, in handle
    job.run(data=None, commit=True)
  File "/source/design_builder/design_builder.py", line 460, in run
    self.implement_design(context, design_file)
  File "/source/design_builder/design_builder.py", line 437, in implement_design
    raise ex
  File "/source/design_builder/design_builder.py", line 434, in implement_design
    self.creator.implement_design(design)
  File "/source/design_builder/object_creator.py", line 430, in implement_design
    self._create_objects(self.model_map[key], value)
  File "/source/design_builder/object_creator.py", line 478, in _create_objects
    CreatorObject(self, model_cls, creator_object)
  File "/source/design_builder/object_creator.py", line 169, in __init__
    self._update_fields()
  File "/source/design_builder/object_creator.py", line 278, in _update_fields
    self.creator.save_model(self)
  File "/source/design_builder/object_creator.py", line 506, in save_model
    model.instance.save()
  File "/usr/local/lib/python3.8/site-packages/nautobot/extras/models/datasources.py", line 125, in save
    transaction.on_commit(on_commit_callback)
  File "/usr/local/lib/python3.8/site-packages/django/db/transaction.py", line 128, in on_commit
    get_connection(using).on_commit(func)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 645, in on_commit
    func()
  File "/usr/local/lib/python3.8/site-packages/nautobot/extras/models/datasources.py", line 109, in on_commit_callback
    assert self.request is not None, "No HTTP request associated with this update!"
AssertionError: No HTTP request associated with this update!
```

**Comment by abates** [comment]
@mzbroch I think this is fixed by #95 . Can you confirm?
